name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: main
      target_name:
        description: "Deployment target (e.g., staging or production)"
        required: true
        default: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (optional for linting/tests)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Deploy Flask app to AWS EC2 using SSH
      - name: Deploy to AWS EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}           # Public IP of EC2 instance
          AWS_USER: ${{ secrets.AWS_USER }}           # EC2 username (e.g., ec2-user)
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Private key for SSH access
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r . $AWS_USER@$AWS_HOST:~/flask-app
          ssh -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
          cd ~/flask-app
          python3 -m pip install -r requirements.txt
          nohup python3 app.py &
          EOF
