name: deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        default: main
      target_name:
        required: false
        default: production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to target
        run: |
          echo "Deploying to ${{ inputs.target }} from ${{ inputs.branch }}"
